# version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scraper:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://username:password@db:5432/hotel_db

volumes:
  postgres_data:
